# Generated by Django 3.2.16 on 2022-11-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Укажите дату публикации', verbose_name='Дата публикации'),
        ),
    ]
