# Generated by Django 3.2 on 2023-03-31 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20230326_1654'),
        ('posts', '0008_auto_20221123_1649'),
    ]

    operations = [
    ]
